[params.staticman]
  enabled             = false
  api                 = "https://staticmantrinity.herokuapp.com/v3/entry/github/cambragol/advent-of-the-trinity/master/comments"  # No Trailing Slash
  gitProvider         = "github"
  username            = "cambragol"
  repo                = "cambragol/advent-of-the-trinity"
  branch              = "master"

  [params.staticman.recaptcha]
    siteKey           = ""
    encryptedKey      = ""
